### ISSUE TITLE
Plugin ignores "uploads: parent:" query

### ISSUE THREAD

**Issue by ac-magma** [dgtl-one/kirby-chunky#8]
I have several fields where I have a custom destination for the uploaded file, such as:

```
fields:
   sponsor_logo:
      type: files
      query: site.find('sponsors')
      uploads:
         parent: site.find('sponsors')
```

The first query is correctly targeted. However, uploads don't land in the specified parent folder. When I remove the plugin, the files are uploaded in the correct folder again, so the issue is with the plugin.
